language: go
sudo: false
go:
  - 1.7
  - 1.8
before_install:
  - go get github.com/IncSW/go-bencode
  - go get github.com/boltdb/bolt
  - go get github.com/valyala/fasthttp
  - go get github.com/stretchr/testify/assert
go_import_path: github.com/IncSW/go-bittorrent-tracker
script:
  - make test
after_success:
  - make coveralls
